backend:
  name: github
  repo: rhuargh/hugo-restaurant-tutorial # Path to your Github repository
  branch: master # Branch to update

media_folder: "srsc/img/gallery"

collections:
  - name: food
    label: food item
    folder: "site/content/food"
    create: true
    fields: 
      - {label: "Name of Item", name: "title", widget: "string"}
      - {label: "Supported Meals", name: "categories", widget: "list", default: ["lunch", "brunch"]}
      - {label: "Ingredients/Description", name: "description", widget: "text"}
      - {label: "Type of Food", name: "type", widget: "string", default: "egg dishes"}
      - {label: "Price", name: "price", widget; "string"}